ticket:ticket.c
	gcc $^ -o $@
BuyAndSaleModel:BuyAndSaleModel.cpp
	g++ -g $^ -o $@ -lpthread
join:join.c
	gcc $^ -o $@ -lpthread
exit:exit.c
	gcc $^ -o $@ -lpthread
create:create.c
	gcc $^ -o $@ -lpthread
